// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridgestate} from '../models';
import {updater} from '../models';
import {app} from '../models';
import {context} from '../models';
import {library} from '../models';
import {config} from '../models';
import {activity} from '../models';
import {bridge} from '../models';
import {ytdlp} from '../models';

export function AutoDownloadToLibrary():Promise<boolean>;

export function BridgeStatus():Promise<bridgestate.State>;

export function BridgeVersion():Promise<string>;

export function BuildDiagnosticReport():Promise<string>;

export function CheckForUpdates():Promise<updater.UpdateInfo>;

export function CookiesPath():Promise<string>;

export function CookiesState():Promise<app.CookiesStatus>;

export function Ctx():Promise<context.Context>;

export function DownloadAudio(arg1:string):Promise<library.Track>;

export function DownloadDir():Promise<string>;

export function ForceYtdlpUpdate():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetStartupProjectFilePath():Promise<string>;

export function GetTrack(arg1:string):Promise<library.Track>;

export function GetYtdlpPath():Promise<string>;

export function InstallUpdate():Promise<void>;

export function LatestUpdate():Promise<updater.UpdateInfo>;

export function LibrarySize():Promise<number>;

export function ListTracks():Promise<Array<library.Track>>;

export function ManifestURL():Promise<string>;

export function MarkQuitting():Promise<void>;

export function OpenInComposer(arg1:string):Promise<string>;

export function OpenInYouTube(arg1:string):Promise<string>;

export function OpenLogFile():Promise<string>;

export function PreferPremiumAudio():Promise<boolean>;

export function ReadProjectFile(arg1:string):Promise<string>;

export function RecentActivity(arg1:number):Promise<Array<activity.Entry>>;

export function RemoveCookies():Promise<void>;

export function RemoveTrack(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SetBridge(arg1:bridge.Bridge):Promise<void>;

export function SetBridgeState(arg1:bridgestate.Holder):Promise<void>;

export function SetCookiesEnabled(arg1:boolean):Promise<void>;

export function SetHasUnsavedChanges(arg1:boolean):Promise<void>;

export function SetLatestUpdate(arg1:updater.UpdateInfo):Promise<void>;

export function SetManifestURL(arg1:string):Promise<void>;

export function SetPreferPremiumAudio(arg1:boolean):Promise<void>;

export function SetStatusEmitter(arg1:any):Promise<void>;

export function SetYtdlpRefresher(arg1:any):Promise<void>;

export function SetYtdlpVersionFn(arg1:any):Promise<void>;

export function SetYtdlpVersionRefresher(arg1:any):Promise<void>;

export function ShowDirectoryDialog(arg1:string):Promise<string>;

export function ShowOpenFileDialog():Promise<string>;

export function ShowSaveFileDialog(arg1:string,arg2:string):Promise<string>;

export function ShowTTMLSaveFileDialog(arg1:string,arg2:string):Promise<string>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartServer():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopServer():Promise<void>;

export function SupportsAutostart():Promise<boolean>;

export function ThumbCacheSize():Promise<number>;

export function UploadCookies(arg1:string):Promise<void>;

export function VerifyCookies():Promise<ytdlp.VerifyResult>;

export function WriteProjectFile(arg1:string,arg2:string):Promise<void>;

export function YtdlpVersion():Promise<string>;
