// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoDownloadToLibrary() {
  return window['go']['app']['App']['AutoDownloadToLibrary']();
}

export function BridgeStatus() {
  return window['go']['app']['App']['BridgeStatus']();
}

export function BridgeVersion() {
  return window['go']['app']['App']['BridgeVersion']();
}

export function BuildDiagnosticReport() {
  return window['go']['app']['App']['BuildDiagnosticReport']();
}

export function CheckForUpdates() {
  return window['go']['app']['App']['CheckForUpdates']();
}

export function CookiesPath() {
  return window['go']['app']['App']['CookiesPath']();
}

export function CookiesState() {
  return window['go']['app']['App']['CookiesState']();
}

export function Ctx() {
  return window['go']['app']['App']['Ctx']();
}

export function DownloadAudio(arg1) {
  return window['go']['app']['App']['DownloadAudio'](arg1);
}

export function DownloadDir() {
  return window['go']['app']['App']['DownloadDir']();
}

export function ForceYtdlpUpdate() {
  return window['go']['app']['App']['ForceYtdlpUpdate']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetStartupProjectFilePath() {
  return window['go']['app']['App']['GetStartupProjectFilePath']();
}

export function GetTrack(arg1) {
  return window['go']['app']['App']['GetTrack'](arg1);
}

export function GetYtdlpPath() {
  return window['go']['app']['App']['GetYtdlpPath']();
}

export function InstallUpdate() {
  return window['go']['app']['App']['InstallUpdate']();
}

export function LatestUpdate() {
  return window['go']['app']['App']['LatestUpdate']();
}

export function LibrarySize() {
  return window['go']['app']['App']['LibrarySize']();
}

export function ListTracks() {
  return window['go']['app']['App']['ListTracks']();
}

export function ManifestURL() {
  return window['go']['app']['App']['ManifestURL']();
}

export function MarkQuitting() {
  return window['go']['app']['App']['MarkQuitting']();
}

export function OpenInComposer(arg1) {
  return window['go']['app']['App']['OpenInComposer'](arg1);
}

export function OpenInYouTube(arg1) {
  return window['go']['app']['App']['OpenInYouTube'](arg1);
}

export function OpenLogFile() {
  return window['go']['app']['App']['OpenLogFile']();
}

export function PreferPremiumAudio() {
  return window['go']['app']['App']['PreferPremiumAudio']();
}

export function ReadProjectFile(arg1) {
  return window['go']['app']['App']['ReadProjectFile'](arg1);
}

export function RecentActivity(arg1) {
  return window['go']['app']['App']['RecentActivity'](arg1);
}

export function RemoveCookies() {
  return window['go']['app']['App']['RemoveCookies']();
}

export function RemoveTrack(arg1) {
  return window['go']['app']['App']['RemoveTrack'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SetBridge(arg1) {
  return window['go']['app']['App']['SetBridge'](arg1);
}

export function SetBridgeState(arg1) {
  return window['go']['app']['App']['SetBridgeState'](arg1);
}

export function SetCookiesEnabled(arg1) {
  return window['go']['app']['App']['SetCookiesEnabled'](arg1);
}

export function SetHasUnsavedChanges(arg1) {
  return window['go']['app']['App']['SetHasUnsavedChanges'](arg1);
}

export function SetLatestUpdate(arg1) {
  return window['go']['app']['App']['SetLatestUpdate'](arg1);
}

export function SetManifestURL(arg1) {
  return window['go']['app']['App']['SetManifestURL'](arg1);
}

export function SetPreferPremiumAudio(arg1) {
  return window['go']['app']['App']['SetPreferPremiumAudio'](arg1);
}

export function SetStatusEmitter(arg1) {
  return window['go']['app']['App']['SetStatusEmitter'](arg1);
}

export function SetYtdlpRefresher(arg1) {
  return window['go']['app']['App']['SetYtdlpRefresher'](arg1);
}

export function SetYtdlpVersionFn(arg1) {
  return window['go']['app']['App']['SetYtdlpVersionFn'](arg1);
}

export function SetYtdlpVersionRefresher(arg1) {
  return window['go']['app']['App']['SetYtdlpVersionRefresher'](arg1);
}

export function ShowDirectoryDialog(arg1) {
  return window['go']['app']['App']['ShowDirectoryDialog'](arg1);
}

export function ShowOpenFileDialog() {
  return window['go']['app']['App']['ShowOpenFileDialog']();
}

export function ShowSaveFileDialog(arg1, arg2) {
  return window['go']['app']['App']['ShowSaveFileDialog'](arg1, arg2);
}

export function ShowTTMLSaveFileDialog(arg1, arg2) {
  return window['go']['app']['App']['ShowTTMLSaveFileDialog'](arg1, arg2);
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function StartServer() {
  return window['go']['app']['App']['StartServer']();
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function StopServer() {
  return window['go']['app']['App']['StopServer']();
}

export function SupportsAutostart() {
  return window['go']['app']['App']['SupportsAutostart']();
}

export function ThumbCacheSize() {
  return window['go']['app']['App']['ThumbCacheSize']();
}

export function UploadCookies(arg1) {
  return window['go']['app']['App']['UploadCookies'](arg1);
}

export function VerifyCookies() {
  return window['go']['app']['App']['VerifyCookies']();
}

export function WriteProjectFile(arg1, arg2) {
  return window['go']['app']['App']['WriteProjectFile'](arg1, arg2);
}

export function YtdlpVersion() {
  return window['go']['app']['App']['YtdlpVersion']();
}
